<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="PublishAot;PublishTrimmed;IlcOptimizationPreference">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
        <PublishAot>false</PublishAot>
        <PublishTrimmed>false</PublishTrimmed>
    </PropertyGroup>

    <Import Project="build\Pixely.SdlangCompiler.props" />

    <Import Project="build\Pixely.SdlangCompiler.targets" />

    <ItemGroup>
        <PackageReference Include="Microsoft.Build.Framework" />
        <PackageReference Include="Microsoft.Build.Utilities.Core" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Pixely.ShaderCommon\Pixely.ShaderCommon.csproj"
                          GlobalPropertiesToRemove="PublishSingleFile" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Pixely.SdlangCompiler.Tests" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>SlangVersion</_Parameter1>
            <_Parameter2>$(SlangVersion)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
