using Pixely.App;

namespace HostedConsumer;

// Main is generated by the package. Configure fails on purpose so the run exercises the generated
// entry point, Configure and OnException without needing a window or a GPU.
static partial class Program
{
    private static partial void Configure(PixelyAppBuilder builder, string[] args)
    {
        Console.WriteLine($"Configure ran with {args.Length} arguments: {string.Join(' ', args)}");
        throw new InvalidOperationException("Configure failed on purpose.");
    }

    static partial void OnException(Exception exception)
    {
        Console.WriteLine($"OnException ran: {exception.Message}");
    }
}
