using Pixely.App;

namespace HostedConsumer;

// Main is generated by the package. Configure fails on purpose so the run exercises the generated
// entry point, Configure and OnException without needing a window or a GPU. The constants select
// the variants PackageIntegrationTests builds.
static partial class Program
{
#if !HOSTED_CONSUMER_NO_CONFIGURE
    static partial void Configure(PixelyAppBuilder builder, string[] args)
    {
        Console.WriteLine($"Configure ran with {args.Length} arguments: {string.Join(' ', args)}");
        throw new InvalidOperationException("Configure failed on purpose.");
    }
#endif

#if !HOSTED_CONSUMER_NO_HANDLER
    static partial void OnException(Exception exception)
    {
        Console.WriteLine($"OnException ran: {exception.Message}");
    }
#endif
}
