using Pixely.App;

namespace HostedConsumer;

// Main is generated by the package. Configure fails on purpose so the run exercises the generated
// entry point, Configure and OnException without needing a window or a GPU. The constants select
// the variants PackageIntegrationTests builds.
static partial class Program
{
#if !HOSTED_CONSUMER_NO_CONFIGURE
    static void Configure(PixelyAppBuilder builder)
    {
#if HOSTED_CONSUMER_NARROW_HANDLER
        // The exception leaves Main unhandled. On Linux the runtime would abort() and leave a core dump; exiting from the
        // event keeps the failure observable through the exit code without one.
        AppDomain.CurrentDomain.UnhandledException += (_, arguments) =>
        {
            Console.WriteLine($"Unhandled: {((Exception)arguments.ExceptionObject).Message}");
            Environment.Exit(3);
        };
#endif
        Console.WriteLine("Configure ran.");
        throw new InvalidOperationException("Configure failed on purpose.");
    }
#endif

#if HOSTED_CONSUMER_NARROW_HANDLER
    // Not applicable to an Exception argument, so lookup falls through to the generated default and this never runs.
    static int OnException(InvalidOperationException exception)
    {
        Console.WriteLine($"OnException ran: {exception.Message}");
        return 1;
    }
#elif !HOSTED_CONSUMER_NO_HANDLER
    static int OnException(Exception exception)
    {
        // The browser test publishes once and picks the outcome at run time: an exception leaving Main rejects runMain().
        if (Environment.GetEnvironmentVariable("HOSTED_CONSUMER_RETHROW") == "1")
        {
            System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(exception);
        }
        Console.WriteLine($"OnException ran: {exception.Message}");
        return 1;
    }
#endif
}
