<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Pixely.DependencyInjection.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Pixely.Collections\Pixely.Collections.csproj" />
      <ProjectReference Include="..\Pixely.Core\Pixely.Core.csproj" />
      <ProjectReference Include="..\Pixely.DependencyInjection\Pixely.DependencyInjection.csproj" />
      <ProjectReference Include="..\Pixely.DependencyInjection.Generator\Pixely.DependencyInjection.Generator.csproj"
                        OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
    </ItemGroup>

    <Import Project="..\Pixely.DependencyInjection.Generator\build\Pixely.DependencyInjection.Generator.props" />

</Project>
