<Project>
    <PropertyGroup>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Pixely.DependencyInjection.Generated</InterceptorsNamespaces>
        <PixelyDocsDirectory>$(MSBuildThisFileDirectory)..\docs\</PixelyDocsDirectory>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="PixelyDIEmitTrimAnnotations" />
    </ItemGroup>

    <Import Project="$(MSBuildThisFileDirectory)..\tools\net10.0\any\build\Pixely.SdlangCompiler.props" />
</Project>
