<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Pixely.Core/Pixely.Core.csproj" />
        <ProjectReference Include="../Pixely.Collections/Pixely.Collections.csproj" />
        <ProjectReference Include="../Pixely.DependencyInjection/Pixely.DependencyInjection.csproj" />
    </ItemGroup>

</Project>
