<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Pixely.DependencyInjection.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
        <PackageReference Include="NUnit" Version="4.6.1"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.14.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Pixely.DependencyInjection\Pixely.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\src\Pixely.DependencyInjection.Generator\Pixely.DependencyInjection.Generator.csproj"
                        OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\..\src\Pixely.Architecture\Pixely.Architecture.csproj" />
    </ItemGroup>

    <Import Project="..\..\src\Pixely.DependencyInjection.Generator\build\Pixely.DependencyInjection.Generator.props" />

</Project>
