<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Pixely\Pixely.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="build\**" />
    </ItemGroup>

</Project>
