<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <Import Project="../../src/Pixely.SdlangCompiler/build/Pixely.SdlangCompiler.props" />
    <Import Project="../../src/Pixely.SdlangCompiler/build/Pixely.SdlangCompiler.targets" />

    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>SlangCompilerPath</_Parameter1>
            <_Parameter2>$(SlangCompilerPath)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit.Analyzers" Version="4.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="TestShaders\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Pixely.SdlangCompiler/Pixely.SdlangCompiler.csproj" />
    </ItemGroup>

    <Target Name="CompileTestSdlangShaders" AfterTargets="CopyFilesToOutputDirectory" DependsOnTargets="ValidateSlangToolchain">
        <ItemGroup>
            <TestSdlangShader Include="$(OutputPath)\TestShaders\*.slang" />
        </ItemGroup>
        <SdlangCompileTask InputFile="%(TestSdlangShader.Identity)" SlangCompilerPath="$(SlangCompilerPath)" />
    </Target>

    <ItemGroup>
        <SdlangShader Include="Content\empty\*.slang" />
    </ItemGroup>

</Project>
