<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Pixely.DependencyInjection.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ppy.SDL3_mixer-CS" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Pixely.Core\Pixely.Core.csproj" />
        <ProjectReference Include="..\Pixely\Pixely.csproj" />
        <ProjectReference Include="..\Pixely.DependencyInjection\Pixely.DependencyInjection.csproj" />
        <ProjectReference Include="..\Pixely.DependencyInjection.Generator\Pixely.DependencyInjection.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
