using Pixely.App;

namespace MultiTargetConsumer;

// Main is generated by the package once per framework. Configure reports the framework it was compiled for and fails on purpose,
// so the run exercises the generated entry point without a window or a GPU.
static partial class Program
{
    static void Configure(PixelyAppBuilder builder)
    {
#if BROWSER
        Console.WriteLine("Configure ran for the browser.");
#else
        Console.WriteLine("Configure ran for the desktop.");
#endif
        throw new InvalidOperationException("Configure failed on purpose.");
    }

    static int OnException(Exception exception)
    {
        Console.WriteLine($"OnException ran: {exception.Message}");
        return 1;
    }
}
